[phases.setup]
nixPkgs = ['nodejs_18', 'yarn']

[phases.install]
cmds = ['yarn install --frozen-lockfile']

[phases.build]
cmds = ['yarn run production']

[start]
cmd = 'npx serve -c serve.json -l $PORT'
