[phases.setup]
nixPkgs = ['nodejs_18', 'yarn']

[phases.install]
cmds = ['yarn install']

[phases.build]
cmds = ['yarn run production']

[start]
cmd = 'npx serve build --single --listen tcp://0.0.0.0:$PORT'
