/* eslint-disable */
export interface RaveCurrency {
  name: string;
  code: string;
  decimalDigits: number;
  currencySymbol: string;
  namePlural: string;
  rounding?: number;
}

export const RaveCurrencyData: RaveCurrency[] = [
  {
    currencySymbol: '$',
    name: 'US Dollar',
    decimalDigits: 2,
    rounding: 0,
    code: 'USD',
    namePlural: 'US dollars',
  },
  {
    currencySymbol: 'CA$',
    name: 'Canadian Dollar',
    decimalDigits: 2,
    rounding: 0,
    code: 'CAD',
    namePlural: 'Canadian dollars',
  },
  {
    currencySymbol: '€',
    name: 'Euro',
    decimalDigits: 2,
    rounding: 0,
    code: 'EUR',
    namePlural: 'euros',
  },
  {
    currencySymbol: 'AED',
    name: 'United Arab Emirates Dirham',
    decimalDigits: 2,
    rounding: 0,
    code: 'AED',
    namePlural: 'UAE dirhams',
  },
  {
    currencySymbol: 'Af',
    name: 'Afghan Afghani',
    decimalDigits: 0,
    rounding: 0,
    code: 'AFN',
    namePlural: 'Afghan Afghanis',
  },
  {
    currencySymbol: 'ALL',
    name: 'Albanian Lek',
    decimalDigits: 0,
    rounding: 0,
    code: 'ALL',
    namePlural: 'Albanian lekë',
  },
  {
    currencySymbol: 'AMD',
    name: 'Armenian Dram',
    decimalDigits: 0,
    rounding: 0,
    code: 'AMD',
    namePlural: 'Armenian drams',
  },
  {
    currencySymbol: 'AR$',
    name: 'Argentine Peso',
    decimalDigits: 2,
    rounding: 0,
    code: 'ARS',
    namePlural: 'Argentine pesos',
  },
  {
    currencySymbol: 'AU$',
    name: 'Australian Dollar',
    decimalDigits: 2,
    rounding: 0,
    code: 'AUD',
    namePlural: 'Australian dollars',
  },
  {
    currencySymbol: 'man.',
    name: 'Azerbaijani Manat',
    decimalDigits: 2,
    rounding: 0,
    code: 'AZN',
    namePlural: 'Azerbaijani manats',
  },
  {
    currencySymbol: 'KM',
    name: 'Bosnia-Herzegovina Convertible Mark',
    decimalDigits: 2,
    rounding: 0,
    code: 'BAM',
    namePlural: 'Bosnia-Herzegovina convertible marks',
  },
  {
    currencySymbol: 'Tk',
    name: 'Bangladeshi Taka',
    decimalDigits: 2,
    rounding: 0,
    code: 'BDT',
    namePlural: 'Bangladeshi takas',
  },
  {
    currencySymbol: 'BGN',
    name: 'Bulgarian Lev',
    decimalDigits: 2,
    rounding: 0,
    code: 'BGN',
    namePlural: 'Bulgarian leva',
  },
  {
    currencySymbol: 'BD',
    name: 'Bahraini Dinar',
    decimalDigits: 3,
    rounding: 0,
    code: 'BHD',
    namePlural: 'Bahraini dinars',
  },
  {
    currencySymbol: 'FBu',
    name: 'Burundian Franc',
    decimalDigits: 0,
    rounding: 0,
    code: 'BIF',
    namePlural: 'Burundian francs',
  },
  {
    currencySymbol: 'BN$',
    name: 'Brunei Dollar',
    decimalDigits: 2,
    rounding: 0,
    code: 'BND',
    namePlural: 'Brunei dollars',
  },
  {
    currencySymbol: 'Bs',
    name: 'Bolivian Boliviano',
    decimalDigits: 2,
    rounding: 0,
    code: 'BOB',
    namePlural: 'Bolivian bolivianos',
  },
  {
    currencySymbol: 'R$',
    name: 'Brazilian Real',
    decimalDigits: 2,
    rounding: 0,
    code: 'BRL',
    namePlural: 'Brazilian reals',
  },
  {
    currencySymbol: 'BWP',
    name: 'Botswanan Pula',
    decimalDigits: 2,
    rounding: 0,
    code: 'BWP',
    namePlural: 'Botswanan pulas',
  },
  {
    currencySymbol: 'Br',
    name: 'Belarusian Ruble',
    decimalDigits: 2,
    rounding: 0,
    code: 'BYN',
    namePlural: 'Belarusian rubles',
  },
  {
    currencySymbol: 'BZ$',
    name: 'Belize Dollar',
    decimalDigits: 2,
    rounding: 0,
    code: 'BZD',
    namePlural: 'Belize dollars',
  },
  {
    currencySymbol: 'CDF',
    name: 'Congolese Franc',
    decimalDigits: 2,
    rounding: 0,
    code: 'CDF',
    namePlural: 'Congolese francs',
  },
  {
    currencySymbol: 'CHF',
    name: 'Swiss Franc',
    decimalDigits: 2,
    rounding: 0.05,
    code: 'CHF',
    namePlural: 'Swiss francs',
  },
  {
    currencySymbol: 'CL$',
    name: 'Chilean Peso',
    decimalDigits: 0,
    rounding: 0,
    code: 'CLP',
    namePlural: 'Chilean pesos',
  },
  {
    currencySymbol: 'CN¥',
    name: 'Chinese Yuan',
    decimalDigits: 2,
    rounding: 0,
    code: 'CNY',
    namePlural: 'Chinese yuan',
  },
  {
    currencySymbol: 'CO$',
    name: 'Colombian Peso',
    decimalDigits: 0,
    rounding: 0,
    code: 'COP',
    namePlural: 'Colombian pesos',
  },
  {
    currencySymbol: '₡',
    name: 'Costa Rican Colón',
    decimalDigits: 0,
    rounding: 0,
    code: 'CRC',
    namePlural: 'Costa Rican colóns',
  },
  {
    currencySymbol: 'CV$',
    name: 'Cape Verdean Escudo',
    decimalDigits: 2,
    rounding: 0,
    code: 'CVE',
    namePlural: 'Cape Verdean escudos',
  },
  {
    currencySymbol: 'Kč',
    name: 'Czech Republic Koruna',
    decimalDigits: 2,
    rounding: 0,
    code: 'CZK',
    namePlural: 'Czech Republic korunas',
  },
  {
    currencySymbol: 'Fdj',
    name: 'Djiboutian Franc',
    decimalDigits: 0,
    rounding: 0,
    code: 'DJF',
    namePlural: 'Djiboutian francs',
  },
  {
    currencySymbol: 'Dkr',
    name: 'Danish Krone',
    decimalDigits: 2,
    rounding: 0,
    code: 'DKK',
    namePlural: 'Danish kroner',
  },
  {
    currencySymbol: 'RD$',
    name: 'Dominican Peso',
    decimalDigits: 2,
    rounding: 0,
    code: 'DOP',
    namePlural: 'Dominican pesos',
  },
  {
    currencySymbol: 'DA',
    name: 'Algerian Dinar',
    decimalDigits: 2,
    rounding: 0,
    code: 'DZD',
    namePlural: 'Algerian dinars',
  },
  {
    currencySymbol: 'Ekr',
    name: 'Estonian Kroon',
    decimalDigits: 2,
    rounding: 0,
    code: 'EEK',
    namePlural: 'Estonian kroons',
  },
  {
    currencySymbol: 'EGP',
    name: 'Egyptian Pound',
    decimalDigits: 2,
    rounding: 0,
    code: 'EGP',
    namePlural: 'Egyptian pounds',
  },
  {
    currencySymbol: 'Nfk',
    name: 'Eritrean Nakfa',
    decimalDigits: 2,
    rounding: 0,
    code: 'ERN',
    namePlural: 'Eritrean nakfas',
  },
  {
    currencySymbol: 'Br',
    name: 'Ethiopian Birr',
    decimalDigits: 2,
    rounding: 0,
    code: 'ETB',
    namePlural: 'Ethiopian birrs',
  },
  {
    currencySymbol: '£',
    name: 'British Pound Sterling',
    decimalDigits: 2,
    rounding: 0,
    code: 'GBP',
    namePlural: 'British pounds sterling',
  },
  {
    currencySymbol: 'GEL',
    name: 'Georgian Lari',
    decimalDigits: 2,
    rounding: 0,
    code: 'GEL',
    namePlural: 'Georgian laris',
  },
  {
    currencySymbol: 'GH₵',
    name: 'Ghanaian Cedi',
    decimalDigits: 2,
    rounding: 0,
    code: 'GHS',
    namePlural: 'Ghanaian cedis',
  },
  {
    currencySymbol: 'FG',
    name: 'Guinean Franc',
    decimalDigits: 0,
    rounding: 0,
    code: 'GNF',
    namePlural: 'Guinean francs',
  },
  {
    currencySymbol: 'GTQ',
    name: 'Guatemalan Quetzal',
    decimalDigits: 2,
    rounding: 0,
    code: 'GTQ',
    namePlural: 'Guatemalan quetzals',
  },
  {
    currencySymbol: 'HK$',
    name: 'Hong Kong Dollar',
    decimalDigits: 2,
    rounding: 0,
    code: 'HKD',
    namePlural: 'Hong Kong dollars',
  },
  {
    currencySymbol: 'HNL',
    name: 'Honduran Lempira',
    decimalDigits: 2,
    rounding: 0,
    code: 'HNL',
    namePlural: 'Honduran lempiras',
  },
  {
    currencySymbol: 'kn',
    name: 'Croatian Kuna',
    decimalDigits: 2,
    rounding: 0,
    code: 'HRK',
    namePlural: 'Croatian kunas',
  },
  {
    currencySymbol: 'Ft',
    name: 'Hungarian Forint',
    decimalDigits: 0,
    rounding: 0,
    code: 'HUF',
    namePlural: 'Hungarian forints',
  },
  {
    currencySymbol: 'Rp',
    name: 'Indonesian Rupiah',
    decimalDigits: 0,
    rounding: 0,
    code: 'IDR',
    namePlural: 'Indonesian rupiahs',
  },
  {
    currencySymbol: '₪',
    name: 'Israeli New Sheqel',
    decimalDigits: 2,
    rounding: 0,
    code: 'ILS',
    namePlural: 'Israeli new sheqels',
  },
  {
    currencySymbol: 'Rs',
    name: 'Indian Rupee',
    decimalDigits: 2,
    rounding: 0,
    code: 'INR',
    namePlural: 'Indian rupees',
  },
  {
    currencySymbol: 'IQD',
    name: 'Iraqi Dinar',
    decimalDigits: 0,
    rounding: 0,
    code: 'IQD',
    namePlural: 'Iraqi dinars',
  },
  {
    currencySymbol: 'IRR',
    name: 'Iranian Rial',
    decimalDigits: 0,
    rounding: 0,
    code: 'IRR',
    namePlural: 'Iranian rials',
  },
  {
    currencySymbol: 'Ikr',
    name: 'Icelandic Króna',
    decimalDigits: 0,
    rounding: 0,
    code: 'ISK',
    namePlural: 'Icelandic krónur',
  },
  {
    currencySymbol: 'J$',
    name: 'Jamaican Dollar',
    decimalDigits: 2,
    rounding: 0,
    code: 'JMD',
    namePlural: 'Jamaican dollars',
  },
  {
    currencySymbol: 'JD',
    name: 'Jordanian Dinar',
    decimalDigits: 3,
    rounding: 0,
    code: 'JOD',
    namePlural: 'Jordanian dinars',
  },
  {
    currencySymbol: '¥',
    name: 'Japanese Yen',
    decimalDigits: 0,
    rounding: 0,
    code: 'JPY',
    namePlural: 'Japanese yen',
  },
  {
    currencySymbol: 'Ksh',
    name: 'Kenyan Shilling',
    decimalDigits: 2,
    rounding: 0,
    code: 'KES',
    namePlural: 'Kenyan shillings',
  },
  {
    currencySymbol: 'KHR',
    name: 'Cambodian Riel',
    decimalDigits: 2,
    rounding: 0,
    code: 'KHR',
    namePlural: 'Cambodian riels',
  },
  {
    currencySymbol: 'CF',
    name: 'Comorian Franc',
    decimalDigits: 0,
    rounding: 0,
    code: 'KMF',
    namePlural: 'Comorian francs',
  },
  {
    currencySymbol: '₩',
    name: 'South Korean Won',
    decimalDigits: 0,
    rounding: 0,
    code: 'KRW',
    namePlural: 'South Korean won',
  },
  {
    currencySymbol: 'KD',
    name: 'Kuwaiti Dinar',
    decimalDigits: 3,
    rounding: 0,
    code: 'KWD',
    namePlural: 'Kuwaiti dinars',
  },
  {
    currencySymbol: 'KZT',
    name: 'Kazakhstani Tenge',
    decimalDigits: 2,
    rounding: 0,
    code: 'KZT',
    namePlural: 'Kazakhstani tenges',
  },
  {
    currencySymbol: 'L.L.',
    name: 'Lebanese Pound',
    decimalDigits: 0,
    rounding: 0,
    code: 'LBP',
    namePlural: 'Lebanese pounds',
  },
  {
    currencySymbol: 'SLRs',
    name: 'Sri Lankan Rupee',
    decimalDigits: 2,
    rounding: 0,
    code: 'LKR',
    namePlural: 'Sri Lankan rupees',
  },
  {
    currencySymbol: 'Lt',
    name: 'Lithuanian Litas',
    decimalDigits: 2,
    rounding: 0,
    code: 'LTL',
    namePlural: 'Lithuanian litai',
  },
  {
    currencySymbol: 'Ls',
    name: 'Latvian Lats',
    decimalDigits: 2,
    rounding: 0,
    code: 'LVL',
    namePlural: 'Latvian lati',
  },
  {
    currencySymbol: 'LD',
    name: 'Libyan Dinar',
    decimalDigits: 3,
    rounding: 0,
    code: 'LYD',
    namePlural: 'Libyan dinars',
  },
  {
    currencySymbol: 'MAD',
    name: 'Moroccan Dirham',
    decimalDigits: 2,
    rounding: 0,
    code: 'MAD',
    namePlural: 'Moroccan dirhams',
  },
  {
    currencySymbol: 'MDL',
    name: 'Moldovan Leu',
    decimalDigits: 2,
    rounding: 0,
    code: 'MDL',
    namePlural: 'Moldovan lei',
  },
  {
    currencySymbol: 'MGA',
    name: 'Malagasy Ariary',
    decimalDigits: 0,
    rounding: 0,
    code: 'MGA',
    namePlural: 'Malagasy Ariaries',
  },
  {
    currencySymbol: 'MKD',
    name: 'Macedonian Denar',
    decimalDigits: 2,
    rounding: 0,
    code: 'MKD',
    namePlural: 'Macedonian denari',
  },
  {
    currencySymbol: 'MMK',
    name: 'Myanma Kyat',
    decimalDigits: 0,
    rounding: 0,
    code: 'MMK',
    namePlural: 'Myanma kyats',
  },
  {
    currencySymbol: 'MOP$',
    name: 'Macanese Pataca',
    decimalDigits: 2,
    rounding: 0,
    code: 'MOP',
    namePlural: 'Macanese patacas',
  },
  {
    currencySymbol: 'MURs',
    name: 'Mauritian Rupee',
    decimalDigits: 0,
    rounding: 0,
    code: 'MUR',
    namePlural: 'Mauritian rupees',
  },
  {
    currencySymbol: 'MX$',
    name: 'Mexican Peso',
    decimalDigits: 2,
    rounding: 0,
    code: 'MXN',
    namePlural: 'Mexican pesos',
  },
  {
    currencySymbol: 'RM',
    name: 'Malaysian Ringgit',
    decimalDigits: 2,
    rounding: 0,
    code: 'MYR',
    namePlural: 'Malaysian ringgits',
  },
  {
    currencySymbol: 'MTn',
    name: 'Mozambican Metical',
    decimalDigits: 2,
    rounding: 0,
    code: 'MZN',
    namePlural: 'Mozambican meticals',
  },
  {
    currencySymbol: 'N$',
    name: 'Namibian Dollar',
    decimalDigits: 2,
    rounding: 0,
    code: 'NAD',
    namePlural: 'Namibian dollars',
  },
  {
    currencySymbol: '₦',
    name: 'Nigerian Naira',
    decimalDigits: 2,
    rounding: 0,
    code: 'NGN',
    namePlural: 'Nigerian nairas',
  },
  {
    currencySymbol: 'C$',
    name: 'Nicaraguan Córdoba',
    decimalDigits: 2,
    rounding: 0,
    code: 'NIO',
    namePlural: 'Nicaraguan córdobas',
  },
  {
    currencySymbol: 'Nkr',
    name: 'Norwegian Krone',
    decimalDigits: 2,
    rounding: 0,
    code: 'NOK',
    namePlural: 'Norwegian kroner',
  },
  {
    currencySymbol: 'NPRs',
    name: 'Nepalese Rupee',
    decimalDigits: 2,
    rounding: 0,
    code: 'NPR',
    namePlural: 'Nepalese rupees',
  },
  {
    currencySymbol: 'NZ$',
    name: 'New Zealand Dollar',
    decimalDigits: 2,
    rounding: 0,
    code: 'NZD',
    namePlural: 'New Zealand dollars',
  },
  {
    currencySymbol: 'OMR',
    name: 'Omani Rial',
    decimalDigits: 3,
    rounding: 0,
    code: 'OMR',
    namePlural: 'Omani rials',
  },
  {
    currencySymbol: 'B/.',
    name: 'Panamanian Balboa',
    decimalDigits: 2,
    rounding: 0,
    code: 'PAB',
    namePlural: 'Panamanian balboas',
  },
  {
    currencySymbol: 'S/.',
    name: 'Peruvian Nuevo Sol',
    decimalDigits: 2,
    rounding: 0,
    code: 'PEN',
    namePlural: 'Peruvian nuevos soles',
  },
  {
    currencySymbol: '₱',
    name: 'Philippine Peso',
    decimalDigits: 2,
    rounding: 0,
    code: 'PHP',
    namePlural: 'Philippine pesos',
  },
  {
    currencySymbol: 'PKRs',
    name: 'Pakistani Rupee',
    decimalDigits: 0,
    rounding: 0,
    code: 'PKR',
    namePlural: 'Pakistani rupees',
  },
  {
    currencySymbol: 'zł',
    name: 'Polish Zloty',
    decimalDigits: 2,
    rounding: 0,
    code: 'PLN',
    namePlural: 'Polish zlotys',
  },
  {
    currencySymbol: '₲',
    name: 'Paraguayan Guarani',
    decimalDigits: 0,
    rounding: 0,
    code: 'PYG',
    namePlural: 'Paraguayan guaranis',
  },
  {
    currencySymbol: 'QR',
    name: 'Qatari Rial',
    decimalDigits: 2,
    rounding: 0,
    code: 'QAR',
    namePlural: 'Qatari rials',
  },
  {
    currencySymbol: 'RON',
    name: 'Romanian Leu',
    decimalDigits: 2,
    rounding: 0,
    code: 'RON',
    namePlural: 'Romanian lei',
  },
  {
    currencySymbol: 'din.',
    name: 'Serbian Dinar',
    decimalDigits: 0,
    rounding: 0,
    code: 'RSD',
    namePlural: 'Serbian dinars',
  },
  {
    currencySymbol: 'RUB',
    name: 'Russian Ruble',
    decimalDigits: 2,
    rounding: 0,
    code: 'RUB',
    namePlural: 'Russian rubles',
  },
  {
    currencySymbol: 'RWF',
    name: 'Rwandan Franc',
    decimalDigits: 0,
    rounding: 0,
    code: 'RWF',
    namePlural: 'Rwandan francs',
  },
  {
    currencySymbol: 'SR',
    name: 'Saudi Riyal',
    decimalDigits: 2,
    rounding: 0,
    code: 'SAR',
    namePlural: 'Saudi riyals',
  },
  {
    currencySymbol: 'SDG',
    name: 'Sudanese Pound',
    decimalDigits: 2,
    rounding: 0,
    code: 'SDG',
    namePlural: 'Sudanese pounds',
  },
  {
    currencySymbol: 'Skr',
    name: 'Swedish Krona',
    decimalDigits: 2,
    rounding: 0,
    code: 'SEK',
    namePlural: 'Swedish kronor',
  },
  {
    currencySymbol: 'S$',
    name: 'Singapore Dollar',
    decimalDigits: 2,
    rounding: 0,
    code: 'SGD',
    namePlural: 'Singapore dollars',
  },
  {
    currencySymbol: 'Ssh',
    name: 'Somali Shilling',
    decimalDigits: 0,
    rounding: 0,
    code: 'SOS',
    namePlural: 'Somali shillings',
  },
  {
    currencySymbol: 'SY£',
    name: 'Syrian Pound',
    decimalDigits: 0,
    rounding: 0,
    code: 'SYP',
    namePlural: 'Syrian pounds',
  },
  {
    currencySymbol: '฿',
    name: 'Thai Baht',
    decimalDigits: 2,
    rounding: 0,
    code: 'THB',
    namePlural: 'Thai baht',
  },
  {
    currencySymbol: 'DT',
    name: 'Tunisian Dinar',
    decimalDigits: 3,
    rounding: 0,
    code: 'TND',
    namePlural: 'Tunisian dinars',
  },
  {
    currencySymbol: 'T$',
    name: 'Tongan Paʻanga',
    decimalDigits: 2,
    rounding: 0,
    code: 'TOP',
    namePlural: 'Tongan paʻanga',
  },
  {
    currencySymbol: 'TL',
    name: 'Turkish Lira',
    decimalDigits: 2,
    rounding: 0,
    code: 'TRY',
    namePlural: 'Turkish Lira',
  },
  {
    currencySymbol: 'TT$',
    name: 'Trinidad and Tobago Dollar',
    decimalDigits: 2,
    rounding: 0,
    code: 'TTD',
    namePlural: 'Trinidad and Tobago dollars',
  },
  {
    currencySymbol: 'NT$',
    name: 'New Taiwan Dollar',
    decimalDigits: 2,
    rounding: 0,
    code: 'TWD',
    namePlural: 'New Taiwan dollars',
  },
  {
    currencySymbol: 'TSh',
    name: 'Tanzanian Shilling',
    decimalDigits: 0,
    rounding: 0,
    code: 'TZS',
    namePlural: 'Tanzanian shillings',
  },
  {
    currencySymbol: '₴',
    name: 'Ukrainian Hryvnia',
    decimalDigits: 2,
    rounding: 0,
    code: 'UAH',
    namePlural: 'Ukrainian hryvnias',
  },
  {
    currencySymbol: 'USh',
    name: 'Ugandan Shilling',
    decimalDigits: 0,
    rounding: 0,
    code: 'UGX',
    namePlural: 'Ugandan shillings',
  },
  {
    currencySymbol: '$U',
    name: 'Uruguayan Peso',
    decimalDigits: 2,
    rounding: 0,
    code: 'UYU',
    namePlural: 'Uruguayan pesos',
  },
  {
    currencySymbol: 'UZS',
    name: 'Uzbekistan Som',
    decimalDigits: 0,
    rounding: 0,
    code: 'UZS',
    namePlural: 'Uzbekistan som',
  },
  {
    currencySymbol: 'Bs.F.',
    name: 'Venezuelan Bolívar',
    decimalDigits: 2,
    rounding: 0,
    code: 'VEF',
    namePlural: 'Venezuelan bolívars',
  },
  {
    currencySymbol: '₫',
    name: 'Vietnamese Dong',
    decimalDigits: 0,
    rounding: 0,
    code: 'VND',
    namePlural: 'Vietnamese dong',
  },
  {
    currencySymbol: 'FCFA',
    name: 'CFA Franc BEAC',
    decimalDigits: 0,
    rounding: 0,
    code: 'XAF',
    namePlural: 'CFA francs BEAC',
  },
  {
    currencySymbol: 'CFA',
    name: 'CFA Franc BCEAO',
    decimalDigits: 0,
    rounding: 0,
    code: 'XOF',
    namePlural: 'CFA francs BCEAO',
  },
  {
    currencySymbol: 'YR',
    name: 'Yemeni Rial',
    decimalDigits: 0,
    rounding: 0,
    code: 'YER',
    namePlural: 'Yemeni rials',
  },
  {
    currencySymbol: 'R',
    name: 'South African Rand',
    decimalDigits: 2,
    rounding: 0,
    code: 'ZAR',
    namePlural: 'South African rand',
  },
  {
    currencySymbol: 'ZK',
    name: 'Zambian Kwacha',
    decimalDigits: 0,
    rounding: 0,
    code: 'ZMK',
    namePlural: 'Zambian kwachas',
  },
  {
    currencySymbol: 'ZWL$',
    name: 'Zimbabwean Dollar',
    decimalDigits: 0,
    rounding: 0,
    code: 'ZWL',
    namePlural: 'Zimbabwean Dollar',
  },
];
