export const LANGUAGES = [
  { title: 'Abkhazian', code: 'ab' },
  { title: 'Afar', code: 'aa' },
  { title: 'Afrikaans', code: 'af' },
  { title: 'Akan', code: 'ak' },
  { title: 'Albanian', code: 'sq' },
  { title: 'Amharic', code: 'am' },
  { title: 'Arabic', code: 'ar' },
  { title: 'Aragonese', code: 'an' },
  { title: 'Armenian', code: 'hy' },
  { title: 'Assamese', code: 'as' },
  { title: 'Avaric', code: 'av' },
  { title: 'Avestan', code: 'ae' },
  { title: 'Aymara', code: 'ay' },
  { title: 'Azerbaijani', code: 'az' },
  { title: 'Bambara', code: 'bm' },
  { title: 'Bashkir', code: 'ba' },
  { title: 'Basque', code: 'eu' },
  { title: 'Belarusian', code: 'be' },
  { title: 'Bengali (Bangla)', code: 'bn' },
  { title: 'Bihari', code: 'bh' },
  { title: 'Bislama', code: 'bi' },
  { title: 'Bosnian', code: 'bs' },
  { title: 'Breton', code: 'br' },
  { title: 'Bulgarian', code: 'bg' },
  { title: 'Burmese', code: 'my' },
  { title: 'Catalan', code: 'ca' },
  { title: 'Chamorro', code: 'ch' },
  { title: 'Chechen', code: 'ce' },
  { title: 'Chichewa, Chewa, Nyanja', code: 'ny' },
  { title: 'Chinese', code: 'zh' },
  { title: 'Chinese (Simplified)', code: 'zh-Hans' },
  { title: 'Chinese (Traditional)', code: 'zh-Hant' },
  { title: 'Chuvash', code: 'cv' },
  { title: 'Cornish', code: 'kw' },
  { title: 'Corsican', code: 'co' },
  { title: 'Cree', code: 'cr' },
  { title: 'Croatian', code: 'hr' },
  { title: 'Czech', code: 'cs' },
  { title: 'Danish', code: 'da' },
  { title: 'Divehi, Dhivehi, Maldivian', code: 'dv' },
  { title: 'Dutch', code: 'nl' },
  { title: 'Dzongkha', code: 'dz' },
  // { title: 'English', code: 'en' },
  { title: 'Esperanto', code: 'eo' },
  { title: 'Estonian', code: 'et' },
  { title: 'Ewe', code: 'ee' },
  { title: 'Faroese', code: 'fo' },
  { title: 'Fijian', code: 'fj' },
  { title: 'Finnish', code: 'fi' },
  { title: 'French', code: 'fr' },
  { title: 'Fula, Fulah, Pulaar, Pular', code: 'ff' },
  { title: 'Galician', code: 'gl' },
  { title: 'Gaelic (Scottish)', code: 'gd' },
  { title: 'Gaelic (Manx)', code: 'gv' },
  { title: 'Georgian', code: 'ka' },
  { title: 'German', code: 'de' },
  { title: 'Greek', code: 'el' },
  { title: 'Greenlandic', code: 'kl' },
  { title: 'Guarani', code: 'gn' },
  { title: 'Gujarati', code: 'gu' },
  { title: 'Haitian Creole', code: 'ht' },
  { title: 'Hausa', code: 'ha' },
  { title: 'Hebrew', code: 'he' },
  { title: 'Herero', code: 'hz' },
  { title: 'Hindi', code: 'hi' },
  { title: 'Hiri Motu', code: 'ho' },
  { title: 'Hungarian', code: 'hu' },
  { title: 'Icelandic', code: 'is' },
  { title: 'Ido', code: 'io' },
  { title: 'Igbo', code: 'ig' },
  { title: 'Indonesian', code: 'in' },
  { title: 'Interlingua', code: 'ia' },
  { title: 'Interlingue', code: 'ie' },
  { title: 'Inuktitut', code: 'iu' },
  { title: 'Inupiak', code: 'ik' },
  { title: 'Irish', code: 'ga' },
  { title: 'Italian', code: 'it' },
  { title: 'Japanese', code: 'ja' },
  { title: 'Javanese', code: 'jv' },
  { title: 'Kalaallisut, Greenlandic', code: 'kl' },
  { title: 'Kannada', code: 'kn' },
  { title: 'Kanuri', code: 'kr' },
  { title: 'Kashmiri', code: 'ks' },
  { title: 'Kazakh', code: 'kk' },
  { title: 'Khmer', code: 'km' },
  { title: 'Kikuyu', code: 'ki' },
  { title: 'Kinyarwanda (Rwanda)', code: 'rw' },
  { title: 'Kirundi', code: 'rn' },
  { title: 'Kyrgyz', code: 'ky' },
  { title: 'Komi', code: 'kv' },
  { title: 'Kongo', code: 'kg' },
  { title: 'Korean', code: 'ko' },
  { title: 'Kurdish', code: 'ku' },
  { title: 'Kwanyama', code: 'kj' },
  { title: 'Lao', code: 'lo' },
  { title: 'Latin', code: 'la' },
  { title: 'Latvian (Lettish)', code: 'lv' },
  { title: 'Limburgish ( Limburger)', code: 'li' },
  { title: 'Lingala', code: 'ln' },
  { title: 'Lithuanian', code: 'lt' },
  { title: 'Luga-Katanga', code: 'lu' },
  { title: 'Luganda, Ganda', code: 'lg' },
  { title: 'Luxembourgish', code: 'lb' },
  { title: 'Manx', code: 'gv' },
  { title: 'Macedonian', code: 'mk' },
  { title: 'Malagasy', code: 'mg' },
  { title: 'Malay', code: 'ms' },
  { title: 'Malayalam', code: 'ml' },
  { title: 'Maltese', code: 'mt' },
  { title: 'Maori', code: 'mi' },
  { title: 'Marathi', code: 'mr' },
  { title: 'Marshallese', code: 'mh' },
  { title: 'Moldavian', code: 'mo' },
  { title: 'Mongolian', code: 'mn' },
  { title: 'Nauru', code: 'na' },
  { title: 'Navajo', code: 'nv' },
  { title: 'Ndonga', code: 'ng' },
  { title: 'Northern Ndebele', code: 'nd' },
  { title: 'Nepali', code: 'ne' },
  { title: 'Norwegian', code: 'no' },
  { title: 'Norwegian bokmål', code: 'nb' },
  { title: 'Norwegian nynorsk', code: 'nn' },
  { title: 'Nuosu', code: 'ii' },
  { title: 'Occitan', code: 'oc' },
  { title: 'Ojibwe', code: 'oj' },
  { title: 'Old Church Slavonic, Old Bulgarian', code: 'cu' },
  { title: 'Oriya', code: 'or' },
  { title: 'Oromo (Afaan Oromo)', code: 'om' },
  { title: 'Ossetian', code: 'os' },
  { title: 'Pāli', code: 'pi' },
  { title: 'Pashto, Pushto', code: 'ps' },
  { title: 'Persian (Farsi)', code: 'fa' },
  { title: 'Polish', code: 'pl' },
  { title: 'Portuguese', code: 'pt' },
  { title: 'Punjabi (Eastern)', code: 'pa' },
  { title: 'Quechua', code: 'qu' },
  { title: 'Romansh', code: 'rm' },
  { title: 'Romanian', code: 'ro' },
  { title: 'Russian', code: 'ru' },
  { title: 'Sami', code: 'se' },
  { title: 'Samoan', code: 'sm' },
  { title: 'Sango', code: 'sg' },
  { title: 'Sanskrit', code: 'sa' },
  { title: 'Serbian', code: 'sr' },
  { title: 'Serbo-Croatian', code: 'sh' },
  { title: 'Sesotho', code: 'st' },
  { title: 'Setswana', code: 'tn' },
  { title: 'Shona', code: 'sn' },
  { title: 'Sichuan Yi', code: 'ii' },
  { title: 'Sindhi', code: 'sd' },
  { title: 'Sinhalese', code: 'si' },
  { title: 'Siswati', code: 'ss' },
  { title: 'Slovak', code: 'sk' },
  { title: 'Slovenian', code: 'sl' },
  { title: 'Somali', code: 'so' },
  { title: 'Southern Ndebele', code: 'nr' },
  { title: 'Spanish', code: 'es' },
  { title: 'Sundanese', code: 'su' },
  { title: 'Swahili (Kiswahili)', code: 'sw' },
  { title: 'Swati', code: 'ss' },
  { title: 'Swedish', code: 'sv' },
  { title: 'Tagalog', code: 'tl' },
  { title: 'Tahitian', code: 'ty' },
  { title: 'Tajik', code: 'tg' },
  { title: 'Tamil', code: 'ta' },
  { title: 'Tatar', code: 'tt' },
  { title: 'Telugu', code: 'te' },
  { title: 'Thai', code: 'th' },
  { title: 'Tibetan', code: 'bo' },
  { title: 'Tigrinya', code: 'ti' },
  { title: 'Tonga', code: 'to' },
  { title: 'Tsonga', code: 'ts' },
  { title: 'Turkish', code: 'tr' },
  { title: 'Turkmen', code: 'tk' },
  { title: 'Twi', code: 'tw' },
  { title: 'Uyghur', code: 'ug' },
  { title: 'Ukrainian', code: 'uk' },
  { title: 'Urdu', code: 'ur' },
  { title: 'Uzbek', code: 'uz' },
  { title: 'Venda', code: 've' },
  { title: 'Vietnamese', code: 'vi' },
  { title: 'Volapük', code: 'vo' },
  { title: 'Wallon', code: 'wa' },
  { title: 'Welsh', code: 'cy' },
  { title: 'Wolof', code: 'wo' },
  { title: 'Western Frisian', code: 'fy' },
  { title: 'Xhosa', code: 'xh' },
  { title: 'Yiddish', code: 'yi, ji' },
  { title: 'Yoruba', code: 'yo' },
  { title: 'Zhuang, Chuang', code: 'za' },
  { title: 'Zulu', code: 'zu' },
];
