// const he = require('he');

export interface CurrencyResponse {
  code: string;
  flag: string;
  symbol: string;
}

// not supported by stripe (commented out)
// BHD BYN EEK ERN GHS IQD IRR JOD KWD LTL LVL LYD OMR SDG SYP TND VEF ZMK ZWL

export const CURRENCIES: CurrencyResponse[] = [
  { code: 'AED', flag: '🇦🇪', /* cc: 'AE', */ symbol: 'د.إ.‏' }, // 'name': 'United Arab Emirates Dirham', 'name_plural': 'UAE dirhams',
  { code: 'AFN', flag: '🇦🇫', /* cc: 'AF', */ symbol: '؋' }, // 'name': 'Afghan Afghani', 'name_plural': 'Afghan Afghanis',
  { code: 'ALL', flag: '🇦🇱', /* cc: 'AL', */ symbol: 'Lek' }, // 'name': 'Albanian Lek', 'name_plural': 'Albanian lekë',
  { code: 'AMD', flag: '🇦🇲', /* cc: 'AM', */ symbol: 'դր.' }, // 'name': 'Armenian Dram', 'name_plural': 'Armenian drams',
  { code: 'ANG', flag: '🇧🇶', /* cc: 'BH', */ symbol: 'ƒ' }, // 'name: '', 'name_plural': '',
  { code: 'AOA', flag: '🇦🇴', /* cc: 'AO', */ symbol: 'Kz' }, // 'name: 'Angolan Kwanza',
  { code: 'ARS', flag: '🇦🇷', /* cc: 'AR', */ symbol: '$' }, // 'name': 'Argentine Peso', 'name_plural': 'Argentine pesos',
  { code: 'AUD', flag: '🇦🇺', /* cc: 'AU', */ symbol: '$' }, // 'name': 'Australian Dollar', 'name_plural': 'Australian dollars',
  { code: 'AWG', flag: '🇦🇼', /* cc: 'AW', */ symbol: 'ƒ' }, // 'name': 'Aruban florin',
  { code: 'AZN', flag: '🇦🇿', /* cc: 'AZ', */ symbol: 'ман.' }, // 'name': 'Azerbaijani Manat', 'name_plural': 'Azerbaijani manats',
  { code: 'BAM', flag: '🇧🇦', /* cc: 'BA', */ symbol: 'KM' }, // 'name': 'Bosnia-Herzegovina Convertible Mark', 'name_plural': 'Bosnia-Herzegovina convertible marks',
  { code: 'BBD', flag: '🇧🇧', /* cc: 'BB', */ symbol: 'Bds$' }, // 'name: 'Barbados Dollar', 'name_plural': '',
  { code: 'BDT', flag: '🇧🇩', /* cc: 'BD', */ symbol: '৳' }, // 'name': 'Bangladeshi Taka', 'name_plural': 'Bangladeshi takas',
  { code: 'BGN', flag: '🇧🇬', /* cc: 'BG', */ symbol: 'лв.' }, // 'name': 'Bulgarian Lev', 'name_plural': 'Bulgarian leva',
  // { code: 'BHD', flag: '🇧🇭', /* cc: 'BH', */ symbol: 'د.ب.‏' }, // 'name': 'Bahraini Dinar', 'name_plural': 'Bahraini dinars',
  { code: 'BIF', flag: '🇧🇮', /* cc: 'BI', */ symbol: 'FBu' }, // 'name': 'Burundian Franc', 'name_plural': 'Burundian francs',
  { code: 'BMD', flag: '🇧🇲', /* cc: 'BM', */ symbol: '$' }, // 'name: 'Bermuda Dollar', 'name_plural': '',
  { code: 'BND', flag: '🇧🇳', /* cc: 'BN', */ symbol: '$' }, // 'name': 'Brunei Dollar', 'name_plural': 'Brunei dollars',
  { code: 'BOB', flag: '🇧🇴', /* cc: 'BO', */ symbol: 'Bs' }, // 'name': 'Bolivian Boliviano', 'name_plural': 'Bolivian bolivianos',
  { code: 'BRL', flag: '🇧🇷', /* cc: 'BR', */ symbol: 'R$' }, // 'name': 'Brazilian Real', 'name_plural': 'Brazilian reals',
  { code: 'BSD', flag: '🇧🇸', /* cc: 'BS', */ symbol: 'B$' }, // 'name: 'Bahamian dollar', 'name_plural': '',
  { code: 'BWP', flag: '🇧🇼', /* cc: 'BW', */ symbol: 'P' }, // 'name': 'Botswanan Pula', 'name_plural': 'Botswanan pulas',
  // { code: 'BYN', flag: '🇧🇾', /* cc: 'BY', */ symbol: 'руб.' },  // 'name': 'Belarusian Ruble', 'name_plural': 'Belarusian rubles',
  { code: 'BZD', flag: '🇧🇿', /* cc: 'BZ', */ symbol: '$' }, // 'name': 'Belize Dollar', 'name_plural': 'Belize dollars',
  { code: 'CAD', flag: '🇨🇦', /* cc: 'CA', */ symbol: '$' }, // 'name': 'Canadian Dollar', 'name_plural': 'Canadian dollars',
  { code: 'CDF', flag: '🇨🇩', /* cc: 'CD', */ symbol: 'FrCD' }, // 'name': 'Congolese Franc', 'name_plural': 'Congolese francs',
  { code: 'CHF', flag: '🇨🇭', /* cc: 'CH', */ symbol: 'CHF' }, // 'name': 'Swiss Franc', 'name_plural': 'Swiss francs',
  { code: 'CLP', flag: '🇨🇱', /* cc: 'CL', */ symbol: '$' }, // 'name': 'Chilean Peso', 'name_plural': 'Chilean pesos',
  { code: 'CNY', flag: '🇨🇳', /* cc: 'CN', */ symbol: 'CN¥' }, // 'name': 'Chinese Yuan', 'name_plural': 'Chinese yuan',
  { code: 'COP', flag: '🇨🇴', /* cc: 'CO', */ symbol: '$' }, // 'name': 'Colombian Peso', 'name_plural': 'Colombian pesos',
  { code: 'CRC', flag: '🇨🇷', /* cc: 'CR', */ symbol: '₡' }, // 'name': 'Costa Rican Colón', 'name_plural': 'Costa Rican colóns',
  { code: 'CVE', flag: '🇨🇻', /* cc: 'CV', */ symbol: 'CV$' }, // 'name': 'Cape Verdean Escudo', 'name_plural': 'Cape Verdean escudos',
  { code: 'CZK', flag: '🇨🇿', /* cc: 'CZ', */ symbol: 'Kč' }, // 'name': 'Czech Republic Koruna', 'name_plural': 'Czech Republic korunas',
  { code: 'DJF', flag: '🇩🇯', /* cc: 'DJ', */ symbol: 'Fdj' }, // 'name': 'Djiboutian Franc', 'name_plural': 'Djiboutian francs',
  { code: 'DKK', flag: '🇩🇰', /* cc: 'DK', */ symbol: 'kr' }, // 'name': 'Danish Krone', 'name_plural': 'Danish kroner',
  { code: 'DOP', flag: '🇩🇴', /* cc: 'DO', */ symbol: 'RD$' }, // 'name': 'Dominican Peso', 'name_plural': 'Dominican pesos',
  { code: 'DZD', flag: '🇩🇿', /* cc: 'DZ', */ symbol: 'د.ج.‏' }, // 'name': 'Algerian Dinar', 'name_plural': 'Algerian dinars',
  // { code: 'EEK', flag: '🇪🇪', /* cc: 'EE', */ symbol: 'kr' },    // 'name': 'Estonian Kroon', 'name_plural': 'Estonian kroons',
  { code: 'EGP', flag: '🇪🇬', /* cc: 'EG', */ symbol: 'ج.م.‏' }, // 'name': 'Egyptian Pound', 'name_plural': 'Egyptian pounds',
  // { code: 'ERN', flag: '🇪🇷', /* cc: 'ER', */ symbol: 'Nfk' },   // 'name': 'Eritrean Nakfa', 'name_plural': 'Eritrean nakfas',
  { code: 'ETB', flag: '🇪🇹', /* cc: 'ET', */ symbol: 'Br' }, // 'name': 'Ethiopian Birr', 'name_plural': 'Ethiopian birrs',
  { code: 'EUR', flag: '🇪🇺', /* cc: 'eu', */ symbol: '€' }, // 'name': 'Euro', 'name_plural': 'euros',
  { code: 'FJD', flag: '🇫🇯', /* cc: 'FJ', */ symbol: 'FJ$' }, // 'name: 'Fijian dollar', 'name_plural': '',
  { code: 'FKP', flag: '🇫🇰', /* cc: 'FK', */ symbol: 'FKP' }, // 'name: 'Falkland Islands pound', 'name_plural': '',
  { code: 'GBP', flag: '🇬🇧', /* cc: 'GB', */ symbol: '£' }, // 'name': 'British Pound Sterling', 'name_plural': 'British pounds sterling',
  { code: 'GEL', flag: '🇬🇪', /* cc: 'GE', */ symbol: 'GEL' }, // 'name': 'Georgian Lari', 'name_plural': 'Georgian laris',
  // { code: 'GHS', flag: '🇬🇭', /* cc: 'GH', */ symbol: 'GH₵' },   // 'name': 'Ghanaian Cedi', 'name_plural': 'Ghanaian cedis',
  { code: 'GIP', flag: '🇬🇮', /* cc: 'GI', */ symbol: '£' }, // 'name: 'Gibraltar pound', 'name_plural': '',
  { code: 'GMD', flag: '🇬🇲', /* cc: 'GM', */ symbol: 'D' }, // 'name: 'Gambian dalasi', 'name_plural': '',
  { code: 'GNF', flag: '🇬🇳', /* cc: 'GN', */ symbol: 'FG' }, // 'name': 'Guinean Franc', 'name_plural': 'Guinean francs',
  { code: 'GTQ', flag: '🇬🇹', /* cc: 'GT', */ symbol: 'Q' }, // 'name': 'Guatemalan Quetzal', 'name_plural': 'Guatemalan quetzals',
  { code: 'GYD', flag: '🇬🇾', /* cc: 'GY', */ symbol: 'G$' }, // 'name: 'Guyanese dollar', 'name_plural': '',
  { code: 'HKD', flag: '🇭🇰', /* cc: 'HK', */ symbol: '$' }, // 'name': 'Hong Kong Dollar', 'name_plural': 'Hong Kong dollars',
  { code: 'HNL', flag: '🇭🇳', /* cc: 'HN', */ symbol: 'L' }, // 'name': 'Honduran Lempira', 'name_plural': 'Honduran lempiras',
  { code: 'HRK', flag: '🇭🇷', /* cc: 'HR', */ symbol: 'kn' }, // 'name': 'Croatian Kuna', 'name_plural': 'Croatian kunas',
  { code: 'HTG', flag: '🇭🇹', /* cc: 'HT', */ symbol: 'G' }, // 'name: 'Haitian gourde', 'name_plural': '',
  { code: 'HUF', flag: '🇭🇺', /* cc: 'HU', */ symbol: 'Ft' }, // 'name': 'Hungarian Forint', 'name_plural': 'Hungarian forints',
  { code: 'IDR', flag: '🇮🇩', /* cc: 'ID', */ symbol: 'Rp' }, // 'name': 'Indonesian Rupiah', 'name_plural': 'Indonesian rupiahs',
  { code: 'ILS', flag: '🇮🇱', /* cc: 'IL', */ symbol: '₪' }, // 'name': 'Israeli New Sheqel', 'name_plural': 'Israeli new sheqels',
  { code: 'INR', flag: '🇮🇳', /* cc: 'IN', */ symbol: 'টকা' }, // 'name': 'Indian Rupee', 'name_plural': 'Indian rupees',
  // { code: 'IQD', flag: '🇮🇶', /* cc: 'IQ', */ symbol: 'د.ع.‏' }, // 'name': 'Iraqi Dinar', 'name_plural': 'Iraqi dinars',
  // { code: 'IRR', flag: '🇮🇷', /* cc: 'IR', */ symbol: '﷼' },     // 'name': 'Iranian Rial', 'name_plural': 'Iranian rials',
  { code: 'ISK', flag: '🇮🇸', /* cc: 'IS', */ symbol: 'kr' }, // 'name': 'Icelandic Króna', 'name_plural': 'Icelandic krónur',
  { code: 'JMD', flag: '🇯🇲', /* cc: 'JM', */ symbol: '$' }, // 'name': 'Jamaican Dollar', 'name_plural': 'Jamaican dollars',
  // { code: 'JOD', flag: '🇯🇴', /* cc: 'JO', */ symbol: 'د.أ.‏' }, // 'name': 'Jordanian Dinar', 'name_plural': 'Jordanian dinars',
  { code: 'JPY', flag: '🇯🇵', /* cc: 'JP', */ symbol: '￥' }, // 'name': 'Japanese Yen', 'name_plural': 'Japanese yen',
  { code: 'KES', flag: '🇰🇪', /* cc: 'KE', */ symbol: 'Ksh' }, // 'name': 'Kenyan Shilling', 'name_plural': 'Kenyan shillings',
  { code: 'KGS', flag: '🇰🇬', /* cc: 'KG', */ symbol: 'Лв' }, // 'name: 'Kyrgyzstani som', 'name_plural': '',
  { code: 'KHR', flag: '🇰🇭', /* cc: 'KH', */ symbol: '៛' }, // 'name': 'Cambodian Riel', 'name_plural': 'Cambodian riels',
  { code: 'KMF', flag: '🇰🇲', /* cc: 'KM', */ symbol: 'FC' }, // 'name': 'Comorian Franc', 'name_plural': 'Comorian francs',
  { code: 'KRW', flag: '🇰🇷', /* cc: 'KR', */ symbol: '₩' }, // 'name': 'South Korean Won', 'name_plural': 'South Korean won',
  // { code: 'KWD', flag: '🇰🇼', /* cc: 'KW', */ symbol: 'د.ك.‏' }, // 'name': 'Kuwaiti Dinar', 'name_plural': 'Kuwaiti dinars',
  { code: 'KYD', flag: '🇰🇾', /* cc: 'KY', */ symbol: '$' }, // 'name: 'Cayman Islands dollar', 'name_plural': '',
  { code: 'KZT', flag: '🇰🇿', /* cc: 'KZ', */ symbol: 'тңг.' }, // 'name': 'Kazakhstani Tenge', 'name_plural': 'Kazakhstani tenges',
  { code: 'LAK', flag: '🇱🇦', /* cc: 'LA', */ symbol: '₭' }, // 'name: 'Lao kip', 'name_plural': '',
  { code: 'LBP', flag: '🇱🇧', /* cc: 'LB', */ symbol: 'ل.ل.‏' }, // 'name': 'Lebanese Pound', 'name_plural': 'Lebanese pounds',
  { code: 'LKR', flag: '🇱🇰', /* cc: 'LK', */ symbol: 'SL Re' }, // 'name': 'Sri Lankan Rupee', 'name_plural': 'Sri Lankan rupees',
  { code: 'LRD', flag: '🇱🇷', /* cc: 'LR', */ symbol: 'L$' }, // 'name: 'Liberian dollar', 'name_plural': '',
  { code: 'LSL', flag: '🇱🇸', /* cc: 'LS', */ symbol: 'M' }, // 'name: 'Lesotho loti', 'name_plural': '',
  // { code: 'LTL', flag: '🇱🇹', /* cc: 'LT', */ symbol: 'Lt' },    // 'name': 'Lithuanian Litas', 'name_plural': 'Lithuanian litai',
  // { code: 'LVL', flag: '🇱🇻', /* cc: 'LV', */ symbol: 'Ls' },    // 'name': 'Latvian Lats', 'name_plural': 'Latvian lati',
  // { code: 'LYD', flag: '🇱🇾', /* cc: 'LY', */ symbol: 'د.ل.‏' }, // 'name': 'Libyan Dinar', 'name_plural': 'Libyan dinars',
  { code: 'MAD', flag: '🇲🇦', /* cc: 'MA', */ symbol: 'د.م.‏' }, // 'name': 'Moroccan Dirham', 'name_plural': 'Moroccan dirhams',
  { code: 'MDL', flag: '🇲🇩', /* cc: 'MD', */ symbol: 'MDL' }, // 'name': 'Moldovan Leu', 'name_plural': 'Moldovan lei',
  { code: 'MGA', flag: '🇲🇬', /* cc: 'MG', */ symbol: 'MGA' }, // 'name': 'Malagasy Ariary', 'name_plural': 'Malagasy Ariaries',
  { code: 'MKD', flag: '🇲🇰', /* cc: 'MK', */ symbol: 'MKD' }, // 'name': 'Macedonian Denar', 'name_plural': 'Macedonian denari',
  { code: 'MMK', flag: '🇲🇲', /* cc: 'MM', */ symbol: 'K' }, // 'name': 'Myanma Kyat', 'name_plural': 'Myanma kyats',
  { code: 'MNT', flag: '🇲🇳', /* cc: 'MN', */ symbol: '₮' }, // 'name: 'Mongolian tögrög', 'name_plural': '',
  { code: 'MOP', flag: '🇲🇴', /* cc: 'MO', */ symbol: 'MOP$' }, // 'name': 'Macanese Pataca', 'name_plural': 'Macanese patacas',
  { code: 'MRO', flag: '🇲🇷', /* cc: 'MR', */ symbol: 'MRU' }, // 'name: 'Mauritanian ouguiya', 'name_plural': '',
  { code: 'MUR', flag: '🇲🇺', /* cc: 'MU', */ symbol: 'MURs' }, // 'name': 'Mauritian Rupee', 'name_plural': 'Mauritian rupees',
  { code: 'MVR', flag: '🇲🇻', /* cc: 'MV', */ symbol: 'Rf' }, // 'name: 'Maldivian rufiyaa', 'name_plural': '',
  { code: 'MWK', flag: '🇲🇼', /* cc: 'MW', */ symbol: 'MK' }, // 'name: 'Malawian kwacha', 'name_plural': '',
  { code: 'MXN', flag: '🇲🇽', /* cc: 'MX', */ symbol: '$' }, // 'name': 'Mexican Peso', 'name_plural': 'Mexican pesos',
  { code: 'MYR', flag: '🇲🇾', /* cc: 'MY', */ symbol: 'RM' }, // 'name': 'Malaysian Ringgit', 'name_plural': 'Malaysian ringgits',
  { code: 'MZN', flag: '🇲🇿', /* cc: 'MZ', */ symbol: 'MTn' }, // 'name': 'Mozambican Metical', 'name_plural': 'Mozambican meticals',
  { code: 'NAD', flag: '🇳🇦', /* cc: 'NA', */ symbol: 'N$' }, // 'name': 'Namibian Dollar', 'name_plural': 'Namibian dollars',
  { code: 'NGN', flag: '🇳🇬', /* cc: 'NG', */ symbol: '₦' }, // 'name': 'Nigerian Naira', 'name_plural': 'Nigerian nairas',
  { code: 'NIO', flag: '🇳🇮', /* cc: 'NI', */ symbol: 'C$' }, // 'name': 'Nicaraguan Córdoba', 'name_plural': 'Nicaraguan córdobas',
  { code: 'NOK', flag: '🇧🇻', /* cc: 'BV', */ symbol: 'kr' }, // 'name': 'Norwegian Krone', 'name_plural': 'Norwegian kroner',
  { code: 'NPR', flag: '🇳🇵', /* cc: 'NP', */ symbol: 'नेरू' }, // 'name': 'Nepalese Rupee', 'name_plural': 'Nepalese rupees',
  { code: 'NZD', flag: '🇳🇿', /* cc: 'NZ', */ symbol: '$' }, // 'name': 'New Zealand Dollar', 'name_plural': 'New Zealand dollars',
  // { code: 'OMR', flag: '🇴🇲', /* cc: 'OM', */ symbol: 'ر.ع.‏' }, // 'name': 'Omani Rial', 'name_plural': 'Omani rials',
  { code: 'PAB', flag: '🇵🇦', /* cc: 'PA', */ symbol: 'B/.' }, // 'name': 'Panamanian Balboa', 'name_plural': 'Panamanian balboas',
  { code: 'PEN', flag: '🇵🇪', /* cc: 'PE', */ symbol: 'S/.' }, // 'name': 'Peruvian Nuevo Sol', 'name_plural': 'Peruvian nuevos soles',
  { code: 'PGK', flag: '🇵🇬', /* cc: 'PG', */ symbol: 'K' }, // 'name: 'Papua New Guinean kina', 'name_plural': '',
  { code: 'PHP', flag: '🇵🇭', /* cc: 'PH', */ symbol: '₱' }, // 'name': 'Philippine Peso', 'name_plural': 'Philippine pesos',
  { code: 'PKR', flag: '🇵🇰', /* cc: 'PK', */ symbol: '₨' }, // 'name': 'Pakistani Rupee', 'name_plural': 'Pakistani rupees',
  { code: 'PLN', flag: '🇵🇱', /* cc: 'PL', */ symbol: 'zł' }, // 'name': 'Polish Zloty', 'name_plural': 'Polish zlotys',
  { code: 'PYG', flag: '🇵🇾', /* cc: 'PY', */ symbol: '₲' }, // 'name': 'Paraguayan Guarani', 'name_plural': 'Paraguayan guaranis',
  { code: 'QAR', flag: '🇶🇦', /* cc: 'QA', */ symbol: 'ر.ق.‏' }, // 'name': 'Qatari Rial', 'name_plural': 'Qatari rials',
  { code: 'RON', flag: '🇷🇴', /* cc: 'RO', */ symbol: 'RON' }, // 'name': 'Romanian Leu', 'name_plural': 'Romanian lei',
  { code: 'RSD', flag: '🇷🇸', /* cc: 'RS', */ symbol: 'дин.' }, // 'name': 'Serbian Dinar', 'name_plural': 'Serbian dinars',
  { code: 'RUB', flag: '🇷🇺', /* cc: 'RU', */ symbol: '₽' }, // 'name': 'Russian Ruble', 'name_plural': 'Russian rubles',
  { code: 'RWF', flag: '🇷🇼', /* cc: 'RW', */ symbol: 'FR' }, // 'name': 'Rwandan Franc', 'name_plural': 'Rwandan francs',
  { code: 'SAR', flag: '🇸🇦', /* cc: 'SA', */ symbol: 'ر.س.‏' }, // 'name': 'Saudi Riyal', 'name_plural': 'Saudi riyals',
  { code: 'SBD', flag: '🇸🇧', /* cc: 'SB', */ symbol: 'Si$' }, // 'name: 'Solomon Islands dollar', 'name_plural': '',
  { code: 'SCR', flag: '🇸🇨', /* cc: '  ', */ symbol: 'SR' }, // 'name: 'Seychellois rupee', 'name_plural': '',
  // { code: 'SDG', flag: '🇸🇩', /* cc: 'SD', */ symbol: 'SDG' },   // 'name': 'Sudanese Pound', 'name_plural': 'Sudanese pounds',
  { code: 'SEK', flag: '🇸🇪', /* cc: 'SE', */ symbol: 'kr' }, // 'name': 'Swedish Krona', 'name_plural': 'Swedish kronor',
  { code: 'SGD', flag: '🇸🇬', /* cc: 'SG', */ symbol: '$' }, // 'name': 'Singapore Dollar', 'name_plural': 'Singapore dollars',
  { code: 'SHP', flag: '🇸🇭', /* cc: 'SH', */ symbol: '£' }, // 'name: 'St Helena Pound', 'name_plural': '',
  { code: 'SLL', flag: '🇸🇱', /* cc: 'SL', */ symbol: 'Le' }, // 'name: 'Sierra Leonean leone', 'name_plural': '',
  { code: 'SOS', flag: '🇸🇴', /* cc: 'SO', */ symbol: 'Ssh' }, // 'name': 'Somali Shilling', 'name_plural': 'Somali shillings',
  { code: 'SRD', flag: '🇸🇷', /* cc: 'SR', */ symbol: '$' }, // 'name: 'Suriname Dollar', 'name_plural': '',
  { code: 'STD', flag: '🇸🇹', /* cc: 'ST', */ symbol: 'Db' }, // 'name: 'São Tomé and Príncipe dobra', 'name_plural': '',
  // { code: 'SYP', flag: '🇸🇾', /* cc: 'SY', */ symbol: 'ل.س.‏' }, // 'name': 'Syrian Pound', 'name_plural': 'Syrian pounds',
  { code: 'SZL', flag: '🇸🇿', /* cc: 'SZ', */ symbol: 'E' }, // 'name: 'Swazi lilangeni', 'name_plural': '',
  { code: 'THB', flag: '🇹🇭', /* cc: 'TH', */ symbol: '฿' }, // 'name': 'Thai Baht', 'name_plural': 'Thai baht',
  { code: 'TJS', flag: '🇹🇯', /* cc: 'TJ', */ symbol: 'ЅM' }, // 'name: 'Tajikistani somoni', 'name_plural': '',
  // { code: 'TND', flag: '🇹🇳', /* cc: 'TN', */ symbol: 'د.ت.‏' }, // 'name': 'Tunisian Dinar', 'name_plural': 'Tunisian dinars',
  { code: 'TOP', flag: '🇹🇴', /* cc: 'TO', */ symbol: 'T$' }, // 'name': 'Tongan Paʻanga', 'name_plural': 'Tongan paʻanga',
  { code: 'TRY', flag: '🇹🇷', /* cc: 'TR', */ symbol: 'TL' }, // 'name': 'Turkish Lira', 'name_plural': 'Turkish Lira',
  { code: 'TTD', flag: '🇹🇹', /* cc: 'TT', */ symbol: '$' }, // 'name': 'Trinidad and Tobago Dollar', 'name_plural': 'Trinidad and Tobago dollars',
  { code: 'TWD', flag: '🇹🇼', /* cc: 'TW', */ symbol: 'NT$' }, // 'name': 'New Taiwan Dollar', 'name_plural': 'New Taiwan dollars',
  { code: 'TZS', flag: '🇹🇿', /* cc: 'TZ', */ symbol: 'TSh' }, // 'name': 'Tanzanian Shilling', 'name_plural': 'Tanzanian shillings',
  { code: 'UAH', flag: '🇺🇦', /* cc: 'UA', */ symbol: '₴' }, // 'name': 'Ukrainian Hryvnia', 'name_plural': 'Ukrainian hryvnias',
  { code: 'UGX', flag: '🇺🇬', /* cc: 'UG', */ symbol: 'USh' }, // 'name': 'Ugandan Shilling', 'name_plural': 'Ugandan shillings',
  { code: 'USD', flag: '🇺🇲', /* cc: 'UM', */ symbol: '$' }, // 'name': 'US Dollar', 'name_plural': 'US dollars',
  { code: 'UYU', flag: '🇺🇾', /* cc: 'UY', */ symbol: '$' }, // 'name': 'Uruguayan Peso', 'name_plural': 'Uruguayan pesos',
  { code: 'UZS', flag: '🇺🇿', /* cc: 'UZ', */ symbol: 'UZS' }, // 'name': 'Uzbekistan Som', 'name_plural': 'Uzbekistan som',
  // { code: 'VEF', flag: '🇻🇪', /* cc: 'VE', */ symbol: 'Bs.F.' }, // 'name': 'Venezuelan Bolívar', 'name_plural': 'Venezuelan bolívars',
  { code: 'VND', flag: '🇻🇳', /* cc: 'VN', */ symbol: '₫' }, // 'name': 'Vietnamese Dong', 'name_plural': 'Vietnamese dong',
  { code: 'VUV', flag: '🇻🇺', /* cc: 'VU', */ symbol: 'VT' }, // 'name: 'Vanuatu vatu', 'name_plural': '',
  { code: 'WST', flag: '🇼🇸', /* cc: 'WS', */ symbol: 'T' }, // 'name: 'Samoan tālā', 'name_plural': '',
  { code: 'XAF', flag: '🇨🇫', /* cc: 'CF', */ symbol: 'FCFA' }, // 'name': 'CFA Franc BEAC', 'name_plural': 'CFA francs BEAC',
  { code: 'XCD', flag: '🇧🇶', /* cc: 'BH', */ symbol: '$' }, // 'name: 'Eastern Caribbean dollar', 'name_plural': '',
  { code: 'XOF', flag: '🇧🇫', /* cc: 'BF', */ symbol: 'CFA' }, // 'name': 'CFA Franc BCEAO', 'name_plural': 'CFA francs BCEAO',
  { code: 'XPF', flag: '🇵🇫', /* cc: 'PF', */ symbol: '₣' }, // 'name: 'CFP franc', 'name_plural': '',
  { code: 'YER', flag: '🇾🇪', /* cc: 'YE', */ symbol: 'ر.ي.‏' }, // 'name': 'Yemeni Rial', 'name_plural': 'Yemeni rials',
  { code: 'ZAR', flag: '🇿🇦', /* cc: 'ZA', */ symbol: 'R' }, // 'name': 'South African Rand', 'name_plural': 'South African rand',
  { code: 'ZMW', flag: '🇿🇲', /* cc: 'ZM', */ symbol: 'ZK' }, // 'name': 'Zambian Kwacha', 'name_plural': 'Zambian kwachas',
  // { code: 'ZWL', flag: '🇿🇼', /* cc: 'ZW', */ symbol: 'ZWL$' },  // 'name': 'Zimbabwean Dollar', 'name_plural': 'Zimbabwean Dollar',
];
